#!/usr/bin/env bash

set -e

basedir="$( cd -P "$( dirname "$0" )" && pwd )"
source "$basedir/../conf/buildpack.conf"
package="$1"

read -p "Enter your FTP user: " FTP_USER
read -p "Enter your FTP password: " FTP_PASS
if [ ${FTP_USER} ] && [ ${FTP_PASS} ]; then
	curl -T ${package} ftp://${FTP_HOST}${FTP_DIR} --user ${FTP_USER}:${FTP_PASS}
	echo "-----> File Uploading complete to re-run ftp-upload run command below"
	echo "support/ftp-upload ${package}"
	echo ""
else
	echo "FTP User or Password is empty, File Uploading cancelled..."
	echo "support/ftp-upload ${package}"
	echo ""
fi
