#!/usr/bin/env bash

set -e

basedir="$( cd -P "$( dirname "$0" )" && pwd )"
source "$basedir/../conf/buildpack.conf"
package="$1"

read -p "Enter your FTP user: " FTP_USER
read -p "Enter your FTP password: " FTP_PASS
if [ ${FTP_USER} ] && [ ${FTP_PASS} ]; then
	echo "curl -v -T ${package} ftp://${FTP_HOST}${FTP_DIR} --user ${FTP_USER}:${FTP_PASS}"
else
	echo "FTP User or Password is empty, exit..."
fi

echo "-----> File Uploaded to FTP Server"
# Tes login: FTPTEST="$(curl ftp://lyric.net23.net --user ewwink:eewjeow)"
#curl -v -T README.md ftp://${FTP_HOST}${FTP_DIR} --user ${FTP_USER}:${FTP_PASS}