#!/usr/bin/env bash

set -e

basedir="$( cd -P "$( dirname "$0" )" && pwd )"
source "$basedir/../conf/buildpack.conf"

package="$1"

tempdir="$( mktemp -t s3_xxxx )"
rm -rf $tempdir
mkdir -p $tempdir
cd $tempdir

echo "-----> Creating checksum for ${package}"

md5 -q "${package}.tgz" > "${package}.md5"
