#!/usr/bin/env bash

set -e

apache_version="$1"

E_ARG_MISSING=127
E_S3_BUCKET_MISSING=2

basedir="$( cd -P "$( dirname "$0" )" && pwd )"
source "$basedir/../conf/buildpack.conf"

export PATH=${basedir}/../vendor/bin:$PATH

if [ -z "$apache_version" ]; then
    echo "Usage: $0 <version>" >&2
    exit $E_ARG_MISSING
fi

if [ -z "$APACHE_PCRE_VERSION" ]; then
    APACHE_PCRE_VERSION=8.34
fi

if [ -z "$APACHE_ZLIB_VERSION" ]; then
    APACHE_ZLIB_VERSION=1.2.8
fi

if [ -z "$APACHE_APR_VERSION" ]; then
    APACHE_APR_VERSION=1.5.0
fi

if [ -z "$APACHE_APR_UTIL_VERSION" ]; then
    APACHE_APR_UTIL_VERSION=1.5.3
fi

pcre_version="$APACHE_PCRE_VERSION"
zlib_version="$APACHE_ZLIB_VERSION"
apr_version="$APACHE_APR_VERSION"
apr_util_version="$APACHE_APR_UTIL_VERSION"

tempdir="$( mktemp -t apache_XXXXXXXX )"
rm -rf $tempdir
mkdir -p $tempdir
cd $tempdir

echo "-----> Downloading dependency zlib ${zlib_version}"

curl -LO "http://zlib.net/zlib-${zlib_version}.tar.gz"
tar -xzvf "zlib-${zlib_version}.tar.gz"

echo "-----> Downloading APACHE ${apache_version}"
curl -LO "http://mirror.symnds.com/software/Apache/httpd/httpd-${apache_version}.tar.gz"
tar -xzvf "httpd-${apache_version}.tar.gz"
cd httpd-${apache_version}
cd srclib

echo "-----> Downloading dependency PCRE ${pcre_version}"

curl -LO "http://sourceforge.net/projects/pcre/files/pcre/${pcre_version}/pcre-${pcre_version}.tar.gz"
tar -xzvf "pcre-${pcre_version}.tar.gz"
mv pcre-${pcre_version} pcre

echo "-----> Downloading dependency APR Utility ${apr_version}"
curl -LO "http://mirror.symnds.com/software/Apache/apr/apr-${apr_version}.tar.gz"
tar -xzvf "apr-${apr_version}.tar.gz"
mv apr-${apr_version} apr

curl -LO "http://mirror.symnds.com/software/Apache/apr/apr-util-${apr_util_version}.tar.gz"
tar -xzvf "apr-util-${apr_util_version}.tar.gz"
mv apr-util-${apr_util_version} apr-util

echo "-----> Compiling Apache"
cd ..
./configure --prefix=/app/vendor/apache \
			--enable-so \
			--enable-rewrite \
			--enable-mods-shared=all \
			--with-zlib=../zlib-${zlib_version} \
			--with-included-apr \
			--enable-expires \
            --enable-headers \
			--enable-deflate \
			--with-included-apr \
			-–with-included-pcre
make
make install
cd /app/vendor/apache
tar -cvzf $tempdir/apache-${apache_version}.tgz .

"$basedir/package-checksum" "$tempdir/httpd-${apache_version}.tgz"

echo "-----> Done building APACHE package! saved as $tempdir/apache-${apache_version}.tgz"

echo "-----------------------------------------------"

echo "---> Uploading package to FTP Server"
while true; do
    read -p "Do you wish to to Upload to FTP Server (y/n)?" yn
    case ${yn} in
        [Yy]* ) "$basedir/ftp-upload" "$tempdir/httpd-${apache_version}.tgz"; break;;
        [Nn]* ) exit;;
        * ) echo "Please answer yes or no.";;
    esac
done
