#!/usr/bin/env bash

set -e

openlitespeed_version="$1"

E_ARG_MISSING=127
E_S3_BUCKET_MISSING=2

basedir="$( cd -P "$( dirname "$0" )" && pwd )"
source "$basedir/../conf/buildpack.conf"

export PATH=${basedir}/../vendor/bin:$PATH

if [ -z "$openlitespeed_version" ]; then
    echo "Usage: $0 <version>" >&2
    exit $E_ARG_MISSING
fi

if [ -z "$PCRE_VERSION" ]; then
    PCRE_VERSION=8.34
fi

if [ -z "$ZLIB_VERSION" ]; then
    ZLIB_VERSION=1.2.8
fi

if [ -z "$EXPAT_VERSION" ]; then
    EXPAT_VERSION=2.1.0
fi


pcre_version="$PCRE_VERSION"
zlib_version="$ZLIB_VERSION"
expat_version="$EXPAT_VERSION"

tempdir="$( mktemp -t openlitespeed_XXXXXXXX )"
rm -rf $tempdir
mkdir -p $tempdir
cd $tempdir

echo "-----> Downloading dependency zlib ${zlib_version}"

curl -LO "http://zlib.net/zlib-${zlib_version}.tar.gz"
tar -xzvf "zlib-${zlib_version}.tar.gz"

echo "-----> Downloading dependency PCRE ${pcre_version}"
curl -LO "http://sourceforge.net/projects/pcre/files/pcre/${pcre_version}/pcre-${pcre_version}.tar.gz"
tar -xzvf "pcre-${pcre_version}.tar.gz"
cd pcre-${pcre_version}
./configure --prefix=/app/vendor/pcre
make
make install
cd ..

echo "-----> Downloading dependency Expat XML Parser ${expat_version}"
curl -LO "http://sourceforge.net/projects/expat/files/expat/${expat_version}/expat-${expat_version}.tar.gz"
tar -xzvf "expat-${expat_version}.tar.gz"
cd expat-${pcre_version}
./configure --prefix=/app/vendor/expat
make
make install
cd ..

echo "-----> Downloading OpenLiteSpeed ${openlitespeed_version}"
curl -LO "http://open.litespeedtech.com/packages/openlitespeed-${openlitespeed_version}.tgz"
tar -xzvf "openlitespeed-${openlitespeed_version}.tar.gz"
cd openlitespeed-${openlitespeed_version}

echo "-----> Compiling OpenLiteSpeed"
cd ..
./configure --prefix=/app/vendor/openlitespeed \
			--with-pcre=/app/vendor/pcre \
			--with-expat=/app/vendor/expat \
			--with-libdir=lib \
			--with-zlib=../zlib-${zlib_version}
			
make
make install
cd /app/vendor/openlitespeed
tar -cvzf $tempdir/openlitespeed-${openlitespeed_version}.tgz .

"$basedir/package-checksum" "$tempdir/openlitespeed-${openlitespeed_version}.tgz"

echo "-----> Done building APACHE package! saved as $tempdir/openlitespeed-${openlitespeed_version}.tgz"

echo "-----------------------------------------------"

echo "---> Uploading package to FTP Server"
while true; do
    read -p "Do you wish to to Upload to FTP Server (y/n)?" yn
    case ${yn} in
        [Yy]* ) "$basedir/ftp-upload" "$tempdir/openlitespeed-${openlitespeed_version}.tgz"; break;;
        [Nn]* ) exit;;
        * ) echo "Please answer yes or no.";;
    esac
done
